apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-demo-app-ingress
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-demo-app-service
                port:
                  number: 80
